# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Translate DOCUMENTATION

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:  # Allow manual triggering for testing

jobs:
  translate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # Don't cancel other jobs if one fails
      matrix:
        language:
          - { code: zh-CN, name: Chinese Simplified }
          - { code: zh-TW, name: Chinese Traditional }
          - { code: hi, name: Hindi }
          - { code: ar, name: Arabic }
          - { code: fr, name: French }
          - { code: de, name: German }
          - { code: nl, name: Dutch }
          - { code: es, name: Spanish }
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      
      # Prepare DOCUMENTATION.md for translation without touching README.md
      - name: Prepare documentation for translation
        run: |
          # The translate-readme action expects a README.md file, so we temporarily rename DOCUMENTATION.md
          if [ -f "DOCUMENTATION.md" ]; then
            # Backup the original README.md if it exists
            if [ -f "README.md" ]; then
              mv README.md README.md.backup
              echo "✅ Backed up original README.md"
            fi
            # Copy DOCUMENTATION.md to README.md for translation
            cp DOCUMENTATION.md README.md
            echo "✅ Temporarily copied DOCUMENTATION.md to README.md for translation"
          else
            echo "❌ DOCUMENTATION.md not found"
            exit 1
          fi
      
      - name: Translate DOCUMENTATION to ${{ matrix.language.name }}
        uses: dephraiim/translate-readme@main
        with:
          LANG: ${{ matrix.language.code }}
      
      # Rename the translated README back to DOCUMENTATION format and restore original README.md
      - name: Process translated file and restore README.md
        run: |
          # Move the translated file to DOCUMENTATION format
          if [ -f "README.${{ matrix.language.code }}.md" ]; then
            mv "README.${{ matrix.language.code }}.md" "DOCUMENTATION.${{ matrix.language.code }}.md"
            echo "✅ Renamed README.${{ matrix.language.code }}.md to DOCUMENTATION.${{ matrix.language.code }}.md"
          else
            echo "❌ Translation failed - README.${{ matrix.language.code }}.md not found"
            exit 1
          fi
          
          # Restore the original README.md
          if [ -f "README.md.backup" ]; then
            mv README.md.backup README.md
            echo "✅ Restored original README.md from backup"
          else
            # Remove the temporary README.md (it was copied from DOCUMENTATION.md)
            rm -f README.md
            echo "✅ Removed temporary README.md"
          fi
      
      - name: Commit translated documentation
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Verify README.md is not modified and restore if needed
          if ! git diff --quiet HEAD -- README.md 2>/dev/null; then
            echo "⚠️ README.md was modified, restoring from HEAD"
            git checkout HEAD -- README.md
          fi
          
          # Double-check that README.md matches what it should be
          git status --porcelain README.md
          
          # Add only the translated DOCUMENTATION file
          git add "DOCUMENTATION.${{ matrix.language.code }}.md"
          
          if git diff --staged --quiet; then
            echo "No changes to commit for ${{ matrix.language.name }}"
          else
            git commit -m "docs: Added DOCUMENTATION.${{ matrix.language.code }}.md translation [skip spacelift]"
            
            # Retry push with pull/rebase in case of conflicts (race conditions)
            for i in {1..3}; do
              if git push; then
                echo "✅ Successfully pushed DOCUMENTATION.${{ matrix.language.code }}.md (attempt $i)"
                break
              else
                echo "⚠️ Push failed (attempt $i), pulling and retrying..."
                git pull --rebase
                # Ensure README.md is still correct after rebase
                if ! git diff --quiet HEAD -- README.md 2>/dev/null; then
                  git checkout HEAD -- README.md
                  echo "⚠️ Restored README.md after rebase"
                fi
                if [ $i -eq 3 ]; then
                  echo "❌ Failed to push after 3 attempts"
                  exit 1
                fi
              fi
            done
          fi
